# This is a basic workflow to help you get started with Actions

name: Trigger Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a Deploy project
      - name: Trigger Aapanel !
        run: |
          echo Starting Trigger
          curl -G "${{ vars.WEBHOOKLPGBACKEND }}" \
          --data-urlencode "token=${{ secrets.WEBHOOK_TOKEN }}" \
          --data-urlencode "repo=${{ github.event.repository.name }}" \
          --data-urlencode "branch=${{ github.ref_name }}"
          echo Trigger Success